version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digio-challenge-app
    ports:
      - "8080:8080" 
    depends_on:
      - redis  
    environment:
      SPRING_REDIS_HOST: redis  
      SPRING_REDIS_PORT: 6379   
    volumes:
      - ./logs:/app/logs  

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  
    restart: unless-stopped
    volumes:
      - redis-data:/data 

volumes:
  redis-data:
